@startuml
skinparam groupInheritance 2

class Member {

}

Class BoardMember

Class Event {

}

Class Conference {

}

Class BoardMeeting

Class Location{

}

Class Person{

}

Class AAUOC {

}

Event <|-- Conference
Event <|-- BoardMeeting

Person <|-- Member
Member <|-- BoardMember

AAUOC o-- "0..*" Person
AAUOC o-- "0..*" Location
AAUOC o-- "0..*"Event

Location "1" -- "0..*" Event : isLocatedIn
Event "0..*" -- "0..*" Member : attendsTo

BoardMeeting "0..*" -- "0..*" BoardMember : attendsTo
Conference "0..*" -- "0..*" Person : attendsTo
@enduml