@startuml
skinparam groupInheritance 2

class Member {
    e-mail : String
}

Class BoardMember

Class Event {
    description : String
    date : Date
    assign(l : Location) : void
}

Class Conference {
    Integer : max_attendees
}

Class BoardMeeting

Class Location{
    description : String
    address : String
}

Class Person{
    e-mail : String
}

Class AAUOC {
    newLocation(I : Location) : void
    newEvent(e : Event) : void
    newPerson(p : Person) : void
    informEvent(e : Event) : void
    register(m : Member,e : Event) : void
}

Event <|-- Conference
Event <|-- BoardMeeting

Person <|-- Member
Member <|-- BoardMember

AAUOC o-- Person
AAUOC o-- Location
AAUOC o-- Event

Location -- Event
Event -- Member

BoardMeeting -- BoardMember
Conference -- Person
@enduml